### ISSUE TITLE
Make the crate rely on the hypervisor crate

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/vfio-ioctls#10]
This is a proposal for making `vfio-ioctls` rely on the `hypervisor` crate (currently defined in `cloud-hypervisor/cloud-hypervisor/hypervisor`).
The point is that we had to manually duplicate a file descriptor with the following [patch](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1867) because the sequence of `Drop` was causing the file descriptor to be closed too early. I consider this more a workaround than a fix because it relies on Linux rather than Rust to do the right thing.

So the proposal for a proper fix would be to ensure that the `Arc<dyn hypervisor::Device>` (the one owning the file descriptor) should be shared with `VfioContainer` [here](https://github.com/cloud-hypervisor/vfio-ioctls/blob/ch/src/vfio_device.rs#L149), so that it would maintain a strong reference until `VfioContainer` is dropped.
From a `vfio-ioctls` perspective, that means it would be dealing with something generic, and couldn't make any assumption about KVM. I'm not sure if this part is right since the KVM_VFIO device is something very much KVM specific :-/

**Comment by sboeuf** [comment]
@jiangliu PTAL

**Comment by jiangliu** [comment]
We are upstreaming the vfio-ioctls crates to rust-vmm, not sure how to deal with the same issue with rust-vmm version.

**Comment by sboeuf** [comment]
I understand, and this doesn't have to happen now, but once the hypervisor crate will be published on `rust-vmm`, do you think it would make sense to have `vfio-ioctls` rely on it?

**Comment by rbradford** [comment]
I don't think it makes sense to depend on the hypervisor crate. It would really heavily dictate how that VMM is implemented. The `dup()` solution is very neat and works well.

**Comment by sboeuf** [comment]
Ok then! Let's close this issue!
