### ISSUE TITLE
get_regions' lower debug level may be more friendly!

### ISSUE THREAD

**Issue by Apokleos** [cloud-hypervisor/vfio-ioctls#7]
When I start cloud-hypervisor with vfio device, I got a debug msg as below:

cloud-hypervisor: 1.093175045s: ERROR:/root/.cargo/git/checkouts/vfio-ioctls-4ac8086fd7be4d50/f6f81ee/src/vfio_device.rs:546 -- Could not get region #8 info

As there is no  VGA Region, and there is no need to pop out a ERROR msg. 
the orgin code as below:
https://github.com/cloud-hypervisor/vfio-ioctls/blob/f6f81ee865cb60a24ad5d4ba8200940ed1d5d1f4/src/vfio_device.rs#L546

maybe, warn!() is better!
`
warn!("Could not get region #{} info", i);
`

**Comment by sameo** [comment]
> maybe, warn!() is better!
> `warn!("Could not get region #{} info", i);`

Agreed. Could you please submit a PR for that?

**Comment by Apokleos** [comment]
Hi, @sameo ,
I am sorry to reply late, and I am happy to submit the PR. 

[My Pull Request: get_regions's lower debug level maybe more friendly.](https://github.com/cloud-hypervisor/vfio-ioctls/pull/8)
I have submitted it, please review my code.

Thx!
